from setuptools import setup, find_packages

setup(
    name='audio-diffusion',
    version='1.0.0',
    url='https://github.com/zqevans/audio-diffusion.git',
    author='Zach Evans',
    packages=find_packages(),    
    install_requires=[
        'a-transformers',
        'accelerate',
        'aeiou',
        'archisound',
        'audio-diffusion-pytorch',
        'audio-encoders-pytorch',
        'audio-metadata',
        'auraloss',
        'einops',
        'ema-pytorch',
        'encodec',
        'k-diffusion',
        'pandas',
        'pedalboard',
        'perceiver-pytorch',
        'prefigure',
        'pyloudnorm',
        'pytorch_lightning', 
        'PyWavelets',
        'quantizer-pytorch',
        'scipy',
        'torch',
        'torchaudio',
        'tqdm',
        'transformers',
        'vector-quantize-pytorch',
        'wandb',
        'cached_conv @ git+https://github.com/caillonantoine/cached_conv.git',
        'udls @ git+https://github.com/caillonantoine/UDLS.git',
    ],
)